// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmuezyhrclnqcaeqzxpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtdWV6eWhyY2xucWNhZXF6eHBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTI0NzgsImV4cCI6MjA2NTI4ODQ3OH0.1-iof0u6ZCnui_G9ppOApwYtQWdSJbLeRj3zjkBs7iA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);